export const INPUT_FILE = "INPUT_FILE";
export const EDIT_CELL ="EDIT_CELL";
export const EDIT_HEADER = "EDIT_HEADER";
export const DATA_LOADED = "DATA_LOADED";
export const MATCHED = "MATCHED";
export const LOAD_STARTED = "LOAD_STARTED";
export const SLIDE_INDEX = "SLIDE_INDEX";
export const COLUMN_MATCHING = "COLUMN_MATCHING";
export const UPDATE_CURRENT = "UPDATE_CURRENT";
export const STORE_SUBMIT = "STORE_SUBMIT";
export const EDIT_DATATYPE = "EDIT_DATATYPE";
export const EDIT_NAME = "EDIT_NAME";
export const GOTO_INDEX = "GOTO_INDEX";
export const CHANGE_CHOICE = "CHANGE_CHOICE";
export const EDIT_STATTYPE = "EDIT_STATTYPE";
export const EDIT_DESCRIPTION = "EDIT_DESCRIPTION"
export const EDIT_SOP = "EDIT_SOP"