export const INPUT_FILE = "INPUT_FILE";
export const EDIT_CELL ="EDIT_CELL";
export const EDIT_HEADER = "EDIT_HEADER";
export const DATA_LOADED = "DATA_LOADED";
export const LOAD_STARTED = "LOAD_STARTED";
export const SLIDE_INDEX = "SLIDE_INDEX";
export const CHANGE_CHOICE = "CHANGE_CHOICE";
export const STRATEGY_VISIBLE = "STRATEGY_VISIBLE";
export const UPLOAD_VISIBLE = "UPLOAD_VISIBLE";
export const EDIT_SUBMIT = "EDIT_SUBMIT";
export const SET_PAGE = "SET_PAGE";
export const GO_TO_PAGE = "GO_TO_PAGE";
export const SET_SEARCH = "SET_SEARCH"
export const GET_CLASS_NAME = "GET_CLASS_NAME"
export const PREPARE_NEXT = "PREPARE_NEXT"
export const ADD_ASSOCIATE = "ADD_ASSOCIATE"
export const GET_ONTOLOGY_NAME = "GET_ONTOLOGY_NAME"
